default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shelter_api_development

test:
  <<: *default
  database: shelter_api_test

production:
  <<: *default
  database: shelter_api_production
